### PR TITLE
Version 0.2.3 improvements.

### PR DESCRIPTION
**Pull request by phpdude**
Hi team,

Thank you for your time, you created nice stuff which I had too, but my version was not "plug-and-play", so I spent some time to add functionality and tests to your library. I hope you like it! :)

Please take a look my changes, approve it, merge and publish new version to allow me use it right now! :)

> 0.2.3
> -----
> 
> * Now `include` function finds parent `globals()` scope automatically
> * added protection against infinite recursion with tests
> * added tests for stackable settings definition. Check settings example in tests/settings/stacked/.

Thanks for your time.

### CODE REVIEW

**Comment by phpdude** [comment]
You can list me in the authors section if you like my contribution :)

**Comment by sobolevn** [comment]
That an amazing work! Thanks you! Could you please also add yourself to the authors, so I can squash everything and merge it?

**Comment by phpdude** [comment]
@sobolevn done!

Also I added remark to README file

https://github.com/sobolevn/django-split-settings/pull/10/files#diff-88b99bb28683bd5b7e3a204826ead112R103

**Comment by phpdude** [comment]
Will you push new version to pypi?

**Comment by phpdude** [comment]
Ah, sorry for the disturb :)

Just checked maybe you forgot it.

**Comment by sobolevn** [comment]
Done!

**Comment by phpdude** [comment]
Amazing! Thanks!

**Pull request merged**
