### PR TITLE
Run tests against Python 3.9

### PR DESCRIPTION
**Pull request by k0t3n**
Add Python 3.9-dev build job to Travis CI

### CODE REVIEW

**Comment by k0t3n** [comment]
Python versions' label from README.md is not updated. See https://github.com/badges/shields/issues/5695

**Comment by k0t3n** [comment]
Same Travis issues as in #232

**Comment by sobolevn** [comment]
@k0t3n thanks a lot!

Can you please moving from travis to github actions? 🙂

**Comment by k0t3n** [comment]
@sobolevn sounds great. I would make it a separate task (even an epic).

**Pull request closed without merging**
